### ISSUE TITLE
Determine cron job necessity

### ISSUE THREAD

**Issue by migreva** [michigan-com/gannett-newsfetch#6]
Right now, we run `gannett-newsfetch` as a cron job every 5 minutes to populate our database with article summaries.

As a result of issue https://github.com/michigan-com/gannett-newsfetch/issues/5, we're going to add functionality to `gannet-newsfetch` that allows it to be run as a process with 5 second sleep cycles

Should the process now be responsible for scraping articles every 5 mins? Or should we continue the cron job idea?

**Comment by travelinreid** [comment]
This needs explication. Your question sounds like "should we run the job
every 5 minutes, or should we run the job every 5 minutes?"

**Comment by migreva** [comment]
Yeah the question more is "what should start the 5 minute job: jenkins? or our supervisor process that stays alive all the time?"

**Comment by migreva** [comment]
We're gonna keep the cron job for now, and now have three processes

### Discovery
_These are processes that discover articles that need to be scraped and summarized_
1. `chartbeat-api`, 
2. `gannett-newsfetch articles`

### Scrape and Summarize
_This process handles **all** articles that need scraped and summarized_
1. `gannett-newsfetch scrape-and-summarize`
